name: Validation
on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [^12.12.0]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Run build
      run: yarn build
